stages:
  - daily_job

daily_job:
  stage: daily_job
  image: python:3.10
  before_script:
    - apt-get update && apt-get install -y ca-certificates
    - pip install requests beautifulsoup4 pymongo python-telegram-bot python-dotenv
  script:
    - python -m crawler.fetch_jobs
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - general-docker
