stages:
  - check
  - daily_job

check_runner_ip:
  stage: check
  image: curlimages/curl
  script:
    - echo "Runner IP is:"
    - curl ifconfig.me
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - general-docker


daily_job:
  stage: daily_job
  image: python:3.10-slim-bullseye
  before_script:
    - apt-get update && apt-get install -y ca-certificates curl openssl
    - pip install --upgrade pip
    # - apt-get update && apt-get install -y ca-certificates
    - pip install requests beautifulsoup4 pymongo python-telegram-bot python-dotenv
  script:
    - python -m crawler.fetch_jobs
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - general-docker
